name: Run Playwright Script Daily with Bun

# Controla cuándo se ejecutará el workflow.
on:
  schedule:
    # Ejecutar todos los días a las 05:00 AM (horario UTC).
    - cron: '0 5 * * *'

  # Permite ejecutar manualmente este workflow desde GitHub Actions.
  workflow_dispatch:

jobs:
  run-playwright:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository.
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Cache Bun installation.
    - name: Cache Bun dependencies
      uses: actions/cache@v3
      with:
        path: ~/.bun
        key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    # 3. Cache Playwright browsers.
    - name: Cache Playwright browsers
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    # 4. Install Bun.
    - name: Install Bun
      run: |
        curl -fsSL https://bun.sh/install | bash
        echo "/home/runner/.bun/bin" >> $GITHUB_PATH

    # 5. Install dependencies with Bun.
    - name: Install dependencies with Bun
      run: bun install

    # 6. Install Playwright browsers.
    - name: Install Playwright browsers
      run: bunx playwright install

    # 7. Run the script using Bun.
    - name: Run Playwright script
      run: bun run index.js

    # 8. Commit and push changes using GitHub Action.
    - name: Commit and Push changes
      uses: ad-m/github-push-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        force: true
        commit_message: "Update data.json via GitHub Actions"
        files: |
          data/data.json
